search_queries: /data/muni/utils/data-collector/topic_wise_search_quries.txt
is_file: true
is_channel_ids: false
percent_match: 40
device: cuda
max_pages: 20
language: hindi
dst_folder_name: /data1/muni/datasets/hindi/yt_data/hindi
download_audio_format: mp3
whisper_model_or_path: small
nemo_model_or_path: stt_hi_conformer_ctc_medium